controller_manager:
  ros__parameters:
    update_rate: 100
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    left_wheel_names: ["left_front_wheel"]
    right_wheel_names: ["right_front_wheel"]

    wheel_separation: 0.40
    wheel_radius: 0.02

joint_broad:
  ros__parameters:
    publish_rate: 100
