controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: false

    diff_cont:
      type: diff_drive_controller/DiffDriveController
    

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    left_wheel_names: ["left_front_wheel", "left_rear_wheel"]
    right_wheel_names: ["right_front_wheel", "right_rear_wheel"]

    wheel_separation: 0.068185
    wheel_radius: 0.0815

    publish_rate: 50.0
    #use_samped_vel: false

