controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: false

    joint_trajectory_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"
    
    one_wheel_trajectory:
      type: "joint_trajectory_controller/JointTrajectoryController"

joint_trajectory_controller:
  ros__parameters:
    joints:
      - right_front_wheel
      - right_rear_wheel
      - left_front_wheel

    command_interfaces:
      - effort

    state_interfaces:
      - effort

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint1:
        trajectory: 0.05
        goal: 0.03

one_wheel_trajectory:
  ros__parameters:
    joints:
      - left_front_wheel
      - left_rear_wheel

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint1:
        trajectory: 2.00
        goal: 0.00